/**
 * forge.mjs — describe a component; the system says whether it may exist, and
 * what it owes.
 *
 *   import { createForge, loadForgeData } from 'uicockpit/forge'
 *   const forge = createForge(await loadForgeData())
 *   forge.resolve('a link above the heading that goes back one step')
 *
 * THE IDEA. A design system's component list is usually a matter of taste, and
 * every new request re-opens the argument. Ours is derived: a component exists
 * because the platform has it (layer 1 — HTML, styled by the floor), because
 * WAI-ARIA APG names the pattern (layer 2), or because a public service ships
 * it (layer 4 — GOV.UK, USWDS, NL Design System). Open UI's census (layer 3) is
 * a check, never a source. The forge is that derivation pointed at a SENTENCE
 * instead of at the kit: it resolves the description against the same four
 * catalogues the build gate reads and returns one of five verdicts, each with a
 * citation the reader can click —
 *
 *   EXISTS    we already ship it: the recipe, its provenance line, its
 *             behaviour contract (APG keys + ARIA), its page.
 *   PLATFORM  the platform has it: the element, and the floor rule that already
 *             styles it. NOT a component — the forge refuses to make one.
 *   CORE      nothing in the kit, but layer 2 or 4 names it: it may exist, and
 *             here is what it owes (the pattern / the service's page) plus a
 *             scaffold recipe composed from the kit's grammar.
 *   CENSUS    only Open UI names it: it may exist as a LOCAL EXTENSION, outside
 *             the core, and the derivation gate will say so. Scaffold too.
 *   NONE      no layer names it. Refused, with the words that were not
 *             understood — so the refusal is about the component, not about
 *             the vocabulary.
 *
 * and a sixth when a sentence names several things we have — COMPOSE — which
 * returns them arranged, primary first.
 *
 * WHAT IT IS NOT. There is no model in here and no guessing: matching is a
 * longest-match over the catalogue names, our component pages, and a
 * translation table (forge-vocabulary.json — 'show more' → Disclosure) whose
 * every target is checked against the catalogues on load. Everything it says is
 * a citation. The generated scaffolds use only tokens the kit ships (checked
 * against the token list on load) and the Role Canvas floors for their look, so
 * "under the rules" is a property of the output, not a hope.
 *
 * WHERE THE DATA COMES FROM. cli/data/forge.json, generated by
 * cockpit/scripts/gen-forge-data.ts from the catalogues, the recipes, apg.ts,
 * COMPONENT_PAGES and derive-provenance — one artefact, checked in the build, so
 * the CLI, the MCP tool and the /forge page cannot answer differently.
 *
 * Zero dependencies and no Node imports at module level: the same file runs in
 * the browser. `loadForgeData()` reaches for node:fs lazily.
 */

/* ── words ────────────────────────────────────────────────────────────────── */

/** The same normaliser derive-provenance and audit:naming use, so a name that
 *  matches there matches here — agreement by construction. */
export const norm = (s) => String(s).toLowerCase().replace(/[\s\-_&/().,]/g, '').replace(/(\w+?)(e|er)?(s|ing)$/, '$1')
/** Every form a name is indexed under: stemmed, bare, bare±plural. */
export const forms = (x) => {
  const bare = String(x).toLowerCase().replace(/[\s\-_&/().,]/g, '')
  return [...new Set([norm(x), bare, bare.replace(/s$/, ''), bare + 's'].filter(Boolean))]
}

/* Words that carry no component meaning. Not a list of subjects — a list of
 * English function words plus the words every description uses ("a component
 * that shows the user…"). An unmatched word that is NOT here is reported as
 * "not understood", which is the honest half of a NONE verdict. */
const STOP = new Set(('a an the this that these those it its of for to in on at by with without from into onto over under and or nor but so if then than as ' +
  'is are was were be been being has have had do does did can could should would will may might must shall ' +
  'i you we they he she me us them my your our their his her one ones some any all each every no not only just also very ' +
  'component components element elements control controls widget widgets thing things ui pattern block piece part parts item items ' +
  'user users visitor visitors person people someone somebody ' +
  'show shows showing display displays displaying let lets lets allow allows allowing make makes making tell tells telling see sees ' +
  'that which who what when where how why whether ' +
  'small large big little new old current next previous other another same different ' +
  'top bottom left right above below before after inside outside between around beside near ' +
  'page pages screen screens app apps site sites website web ' +
  'need needs needed want wants wanted like likes ' +
  'kind sort type way ' +
  'i\'d i\'m we\'d please something anything ' +
  'two three four five six several many few more most less least ' +
  'main primary secondary section sections area areas region regions').split(/\s+/))

/** Words, lower-cased, punctuation dropped, hyphenated pairs kept AND split. */
export function tokenize(text) {
  const raw = String(text).toLowerCase().replace(/[“”"'`]/g, '').replace(/[^a-z0-9+\-/ ]+/g, ' ')
  const out = []
  for (const w of raw.split(/\s+/).filter(Boolean)) out.push(w)
  return out
}

/* ── the index ─────────────────────────────────────────────────────────────── */

const LAYER_NAME = { 1: 'MDN · HTML', 2: 'WAI-ARIA APG', 3: 'Open UI', 4: 'public services' }

/**
 * Build a forge over the data. Throws if a vocabulary target names nothing —
 * the same guard derive-provenance puts on its alias keys: an alias that
 * matches nothing is a phantom, and a phantom in a translation table means a
 * whole class of sentences silently resolves to NONE.
 */
export function createForge(data) {
  if (!data || !data.catalogues || !data.kit) throw new Error('createForge: pass the object from cli/data/forge.json')
  const index = new Map()               // form → Concept[]
  const add = (key, c) => { if (!key) return; const k = String(key); if (!index.has(k)) index.set(k, []); if (!index.get(k).includes(c)) index.get(k).push(c) }
  const addForms = (name, c) => { for (const f of forms(name)) add(f, c) }

  /* recipes + pages (the kit) */
  const recipes = data.kit.recipes
  const byId = new Map(recipes.map((r) => [r.id, r]))
  const recipeConcept = new Map()
  for (const r of recipes) {
    const c = { kind: 'recipe', id: r.id, name: r.page?.name ?? r.section, recipe: r }
    recipeConcept.set(r.id, c)
    addForms(r.id, c)
    addForms(r.section, c)
    if (r.block) addForms(r.block, c)
    for (const pg of r.pages ?? (r.page ? [r.page] : [])) { addForms(pg.name, c); addForms(pg.slug, c) }
  }

  /* layer 1 — HTML elements. `input[type=text]` is indexed as "text input" and
   * "input text"; bare "text" would swallow every sentence. Generic containers
   * (div, span, ul, li…) are building material and are not indexed as concepts. */
  const html = data.catalogues.html
  const htmlConcepts = []
  const SKIP = new Set(['search', 'form', 'picture', 'optgroup', 'thead'])         // wrappers / no-render — building material, never an answer
  const EXACT_ONLY = new Set(['li', 'dt', 'dd', 'td', 'th', 'label', 'summary', 'caption', 'figcaption', 'legend'])
  for (const group of ['controls', 'structure', 'content']) {
    for (const [name, path] of Object.entries(html[group] ?? {})) {
      const isAttr = name.startsWith('[')
      const tag = isAttr ? name : name.replace(/\[.*$/, '')
      const type = (name.match(/type=([a-z-]+)/) || [])[1]
      const c = { kind: 'html', layer: 1, name, tag, type, isAttr, group, url: html.url + path }
      htmlConcepts.push(c)
      if (isAttr) { add(name, c); addForms(name.replace(/[[\]]/g, ''), c); continue }
      if (type) { addForms(`${type} input`, c); addForms(`input ${type}`, c); addForms(name, c); continue }
      if (SKIP.has(tag)) continue
      if (EXACT_ONLY.has(tag)) { add(tag, c); continue }   // reachable by its exact tag only
      addForms(tag, c)
    }
  }
  const floorFor = (tag) => data.floor.filter((f) => f.selector.split(',').some((s) => {
    const t = s.trim()
    return t === tag || t.startsWith(tag + '[') || t.startsWith(tag + ':') || t.startsWith(tag + ' ') || t.startsWith(tag + '::')
  })).sort((a, b) => a.selector.split(',').length - b.selector.split(',').length)   // the rule ABOUT this element first, the shared reset last
  const htmlByName = new Map(htmlConcepts.map((c) => [c.name, c]))
  /* The layers OVERLAP (data/derivation-decisions.json): NL's "Heading" IS <h1>,
   * Open UI's "Textarea" IS <textarea>. A catalogue name on that map resolves to
   * the element as well, so the answer is PLATFORM — the same reading the
   * derivation gate makes. */
  const overlapElement = (name) => {
    for (const f of forms(name)) {
      const el = data.overlap?.[f]
      if (el) return htmlByName.get(el) ?? htmlByName.get(el.replace(/\[.*/, '')) ?? { kind: 'html', layer: 1, name: el, tag: el.replace(/\[.*$/, ''), type: (el.match(/type=([a-z-]+)/) || [])[1], group: 'controls', url: html.url }
    }
    return null
  }
  const decidedReason = (name) => data.decided?.[name] ?? null
  const tokenReason = (name) => data.tokenCovered?.[name] ?? null

  /* layer 2 — APG patterns. "Dialog (Modal)" is reachable as dialog, modal and
   * dialogmodal; "Slider (Multi-Thumb)" as slider multi thumb / multithumb. */
  const apg = data.catalogues.apg
  for (const [name, path] of Object.entries(apg.patterns)) {
    const c = { kind: 'apg', layer: 2, name, url: apg.url.replace(/\/patterns\/$/, '') + path }
    addForms(name, c)
    const m = name.match(/^(.*?)\s*\((.*)\)$/)
    if (m) { addForms(m[1], c); addForms(m[2], c) }
  }

  /* layer 3 — Open UI's census. */
  const ou = data.catalogues.openui
  for (const [concept, v] of Object.entries(ou.names)) {
    const c = { kind: 'openui', layer: 3, name: v.spelled, pct: v.pct, systems: v.systems, of: ou.systems, url: ou.url }
    addForms(v.spelled, c); addForms(concept, c)
  }

  /* layer 4 — the service systems, components and page patterns. */
  for (const [system, sv] of Object.entries(data.catalogues.services)) {
    const base = sv.url.replace(/\/[^/]*\/?$/, '')
    for (const kind of ['components', 'patterns']) {
      for (const [name, path] of Object.entries(sv[kind] ?? {})) {
        addForms(name, { kind: 'service', layer: 4, system, name, pattern: kind === 'patterns', url: base + path })
      }
    }
  }

  /* Which recipes COVER a catalogue entry — joined on the URL the provenance
   * line carries (APG, services), on the name for Open UI, and on the element
   * for layer 1. This is what turns "GOV.UK · Back link" into EXISTS. */
  const coversUrl = new Map(), coversName = new Map(), coversOpenui = new Map(), coversElement = new Map()
  const push = (map, key, id) => { if (!key) return; if (!map.has(key)) map.set(key, new Set()); map.get(key).add(id) }
  /* Two joins, because the provenance line does not always carry a URL (the
   * Landmarks anchor points at an APG practices page and its URL is not
   * captured) — so the source NAME is a key too, in the same normalised form:
   * "APG · Landmarks" → apg:landmark; "GOV.UK · Phase banner" → govuk:phasebanner.
   * `covers` is EVERY entry a recipe matched, not just the line it reports. */
  const nameKey = (system, name) => `${norm(system)}:${norm(name)}`
  for (const r of recipes) {
    for (const s of r.provenance ?? []) {
      if (s.url && s.layer !== 3) push(coversUrl, s.url, r.id)
      const m = s.source.match(/^([^·]+) · (.+)$/)
      if (m && s.layer !== 3) push(coversName, nameKey(m[1].trim(), m[2].trim().replace(/\s*\(.*\)$/, '')), r.id)
      if (s.layer === 3) push(coversOpenui, norm(s.source.replace(/^Open UI · /, '')), r.id)
      if (s.layer === 1) push(coversElement, s.source.replace(/^<|>$/g, ''), r.id)
    }
    for (const c of r.covers?.service ?? []) { const m = c.match(/^([^·]+) · (.+)$/); if (m) push(coversName, nameKey(m[1].trim(), m[2].trim()), r.id) }
    for (const c of r.covers?.openui ?? []) push(coversOpenui, norm(c), r.id)
    if (r.element) push(coversElement, r.element, r.id)
  }
  const recipesFor = (c) => {
    if (c.kind === 'recipe') return [c.id]
    if (c.kind === 'html') return [...(coversElement.get(c.tag) ?? []), ...(c.type ? coversElement.get(`${c.tag}[type=${c.type}]`) ?? [] : [])]
    if (c.kind === 'openui') return [...(coversOpenui.get(norm(c.name)) ?? [])]
    const byName = coversName.get(nameKey(c.kind === 'apg' ? 'APG' : c.system, c.name.replace(/\s*\(.*\)$/, ''))) ?? new Set()
    return [...new Set([...(coversUrl.get(c.url) ?? []), ...byName])]
  }

  /* the translation table — every target must land, or the table is a hole. */
  const vocab = new Map()
  const misses = []
  for (const [phrase, targets] of Object.entries(data.vocabulary)) {
    const concepts = []
    for (const t of targets) {
      let hit = null
      for (const f of forms(t)) { if (index.has(f)) { hit = index.get(f); break } }
      if (!hit && index.has(t)) hit = index.get(t)
      if (!hit) { misses.push(`${phrase} → ${t}`); continue }
      for (const c of hit) if (!concepts.includes(c)) concepts.push(c)
    }
    vocab.set(phrase.replace(/\s+/g, ' ').trim(), { concepts, deliberatelyEmpty: targets.length === 0 })
  }
  if (misses.length) throw new Error(`forge vocabulary: ${misses.length} target(s) name nothing in the catalogues — ${misses.slice(0, 8).join('; ')}`)

  const tokenSet = new Set(data.tokens ?? [])

  /* ── matching ──────────────────────────────────────────────────────────── */

  /** Greedy longest-match, four words down to one. A span is the words that
   *  matched and every concept they name; the rest is stopwords or unknown. */
  function match(text) {
    const words = tokenize(text)
    const spans = []
    const unknown = []
    let i = 0
    while (i < words.length) {
      let hit = null
      for (let n = Math.min(4, words.length - i); n >= 1; n--) {
        const phrase = words.slice(i, i + n).join(' ')
        if (n === 1 && STOP.has(phrase) && words.length > 1) break   // "page" alone is a question; "the page" is not
        const v = vocab.get(phrase) ?? vocab.get(phrase.replace(/s$/, '')) ?? null
        /* The kit's own names FIRST, then the translation table — a page named
         * "Data Table" is a direct hit and outranks the catalogue entries the
         * phrase also translates to; the table adds, it never replaces. */
        let concepts = []
        let deliberatelyEmpty = v?.deliberatelyEmpty ?? false
        for (const f of forms(phrase)) if (index.has(f)) { for (const c of index.get(f)) if (!concepts.includes(c)) concepts.push(c) }
        if (v) for (const c of v.concepts) if (!concepts.includes(c)) concepts.push(c)
        // a hyphenated word tried as its halves: "drop-down", "pop-up"
        if (!concepts.length && n === 1 && phrase.includes('-')) {
          const j = phrase.replace(/-/g, ' ')
          const vj = vocab.get(j)
          if (vj) { concepts = [...vj.concepts]; deliberatelyEmpty = vj.deliberatelyEmpty }
        }
        if (concepts.length || deliberatelyEmpty) { hit = { text: phrase, n, concepts, deliberatelyEmpty }; break }
      }
      if (hit) { spans.push(hit); i += hit.n; continue }
      if (!STOP.has(words[i]) && !/^\d+$/.test(words[i])) unknown.push(words[i])
      i++
    }
    return { words, spans, unknown }
  }

  /* ── classifying a span ────────────────────────────────────────────────── */

  const TIER_RANK = { section: 3, component: 2, atom: 1, foundation: 0 }
  function classify(span) {
    const recipeIds = new Set()
    for (const c of span.concepts) for (const id of recipesFor(c)) recipeIds.add(id)
    const rs = [...recipeIds].map((id) => byId.get(id)).filter(Boolean)
      .sort((a, b) => (TIER_RANK[b.tier] - TIER_RANK[a.tier]) || ((b.page ? 1 : 0) - (a.page ? 1 : 0)))
    // A recipe named DIRECTLY (its own name/page) outranks one reached through a
    // catalogue entry it merely covers: "button" is the Button, not the toolbar.
    const direct = span.concepts.filter((c) => c.kind === 'recipe').map((c) => byId.get(c.id)).filter(Boolean)
    const ordered = [...direct, ...rs.filter((r) => !direct.includes(r))]
    const platform = span.concepts.filter((c) => c.kind === 'html')
    // a service / census / APG name that IS a platform element counts as one
    for (const c of span.concepts) {
      if (c.kind === 'html' || c.kind === 'recipe') continue
      const el = overlapElement(c.name)
      if (el && !platform.includes(el)) platform.push(el)
    }
    const decided = span.concepts.map((c) => (c.kind !== 'recipe' && decidedReason(c.name)) ? { name: c.name, reason: decidedReason(c.name), cite: c } : null).filter(Boolean)
    const token = span.concepts.map((c) => (c.kind !== 'recipe' && tokenReason(c.name)) ? { name: c.name, tokens: tokenReason(c.name), cite: c } : null).filter(Boolean)
    return {
      text: span.text,
      recipes: ordered,
      direct: direct.length > 0,
      platform,
      core: span.concepts.filter((c) => c.kind === 'apg' || c.kind === 'service'),
      patterns: span.concepts.filter((c) => c.kind === 'service' && c.pattern),
      census: span.concepts.filter((c) => c.kind === 'openui'),
      decided,
      token,
      deliberatelyEmpty: span.deliberatelyEmpty,
    }
  }

  /* ── citations ─────────────────────────────────────────────────────────── */
  const cite = (c) => {
    if (c.kind === 'html') return { layer: 1, source: c.isAttr ? `the ${c.name} attribute` : `<${c.tag}>${c.type ? ` type=${c.type}` : ''}`, name: c.name, url: c.url }
    if (c.kind === 'apg') return { layer: 2, source: `APG · ${c.name}`, name: c.name, url: c.url }
    if (c.kind === 'openui') return { layer: 3, source: `Open UI · ${c.name}`, name: c.name, url: c.url, note: `${c.systems} of ${c.of} surveyed systems (${c.pct}%)` }
    if (c.kind === 'service') return { layer: 4, source: `${c.system} · ${c.name}${c.pattern ? ' (pattern)' : ''}`, name: c.name, url: c.url, pattern: c.pattern }
    return null
  }

  /* ── generation: skeletons from the kit's own classes, scaffolds from the
   *    grammar. Tokens are checked against the kit's list on the way out. ── */
  const T = (name) => { if (!tokenSet.has(name)) throw new Error(`forge scaffold uses ${name}, which the kit does not ship`); return `var(${name})` }
  const esc = (s) => String(s).replace(/[<>&]/g, (ch) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' }[ch]))
  const title = (s) => String(s).replace(/[-_]+/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase())

  /** A usage skeleton for a recipe we ship: the block on its element, its parts
   *  nested, the ARIA the contract names as a comment. Not a specimen — the
   *  gallery has those — a shape an agent can fill. */
  const PART_RANK = (p) => /head|title|header|label|lead|eyebrow|summary|trigger|handle/.test(p) ? 0 : /foot|footer|action|bar|toolbar|controls|nav|pager/.test(p) ? 2 : 1
  /* When layer 1 was not measured for a recipe, the APG pattern still says what
   * element it is: a Link is an <a>, a Button is a <button>. Facts about the
   * patterns, not a list of our subjects. */
  const PATTERN_ELEMENT = { Link: 'a', Button: 'button', Checkbox: 'input', Switch: 'button', Meter: 'meter', 'Dialog (Modal)': 'dialog', 'Alert Dialog': 'dialog', Table: 'table', Slider: 'input' }
  // …but only for a LEAF: a block with parts is a container, whatever pattern it
  // anchors to (a task list anchors to Checkbox and is not an <input>).
  const elementOf = (r) => r.element ?? ((r.parts?.length ? null : PATTERN_ELEMENT[r.apg?.pattern]) ?? 'div')
  function skeleton(r, children = []) {
    const el = elementOf(r)
    // Parts, not modifiers of parts (`datatable__bar--active` is a state); in a
    // head → body → foot order rather than authored order, four at most.
    const parts = [...new Set((r.parts ?? []).filter((p) => !p.includes('--')))].sort((a, b) => PART_RANK(a) - PART_RANK(b)).slice(0, 4)
    const lines = []
    if (r.apg?.aria?.length) lines.push(`<!-- ${r.apg.pattern}: ${r.apg.aria.slice(0, 3).join(' · ').replace(/--/g, '—')} -->`)
    const open = `<${el} class="${r.block ?? r.id}"${el === 'button' ? ' type="button"' : el === 'a' ? ' href="#"' : ''}>`
    if (!parts.length && !children.length) return [...lines, `${open}${esc(r.page?.name ?? r.section)}</${el}>`].join('\n')
    lines.push(open)
    /* Composed children go where they belong: controls into an actions/foot
     * part, everything else into the body part — when the block has one. */
    const indent = (h, n) => h.split('\n').map((l) => ' '.repeat(n) + l).join('\n')
    const bodyPart = parts.find((p) => PART_RANK(p) === 1)
    const footPart = parts.find((p) => PART_RANK(p) === 2)
    const isControl = (h) => /^(<!--[^]*?-->\n)?<(button|a |input|select|textarea)/.test(h)
    const placed = new Set()
    for (const p of parts) {
      const mine = children.filter((ch) => !placed.has(ch) && ((p === footPart && isControl(ch)) || (p === bodyPart && (!footPart || !isControl(ch)))))
      if (mine.length) {
        lines.push(`  <div class="${p}">`)
        for (const ch of mine) { lines.push(indent(ch, 4)); placed.add(ch) }
        lines.push(`  </div>`)
      } else lines.push(`  <div class="${p}">${esc(title(p.split('__')[1] ?? p))}</div>`)
    }
    for (const ch of children) if (!placed.has(ch)) lines.push(indent(ch, 2))
    lines.push(`</${el}>`)
    return lines.join('\n')
  }

  /** A platform element as it is written — for a composition that includes one. */
  function elementSnippet(c) {
    const t = c.tag
    if (c.isAttr) return `<div popover id="tip">…</div>\n<button type="button" popovertarget="tip">Open</button>`
    if (t === 'input') return `<input type="${c.type ?? 'text'}"${c.type === 'checkbox' || c.type === 'radio' ? '' : ' class="in"'}>`
    if (t === 'img') return `<img src="…" alt="">`
    if (t === 'a') return `<a href="#">Link</a>`
    if (t === 'button') return `<button type="button" class="btn">Action</button>`
    if (t === 'select') return `<select class="select"><option>One</option><option>Two</option></select>`
    if (t === 'textarea') return `<textarea class="in tx"></textarea>`
    if (t === 'details') return `<details><summary>Show more</summary>…</details>`
    if (t === 'dialog') return `<dialog>…</dialog>`
    if (t === 'progress') return `<progress value="30" max="100"></progress>`
    if (t === 'meter') return `<meter value="0.6"></meter>`
    if (t === 'hr') return `<hr>`
    if (t === 'table') return `<table class="table"><thead><tr><th>…</th></tr></thead><tbody><tr><td>…</td></tr></tbody></table>`
    if (t === 'ul' || t === 'ol') return `<${t}><li>…</li></${t}>`
    if (t === 'dl') return `<dl><dt>Term</dt><dd>Definition</dd></dl>`
    if (t === 'blockquote') return `<blockquote><p>…</p></blockquote>`
    if (t === 'figure') return `<figure><img src="…" alt=""><figcaption>…</figcaption></figure>`
    if (/^h[1-6]$/.test(t)) return `<${t}>Heading</${t}>`
    return `<${t}>…</${t}>`
  }

  /** The Role Canvas roles a NEW component's parts wear, read off its name.
   *  A translation into the six roles the kit binds generatively — not a
   *  design: the look is the floor's, the recipe owns arrangement. */
  function rolesFor(name) {
    const n = String(name).toLowerCase()
    if (/dialog|modal|drawer|sheet|popover|toast|tooltip|snackbar|lightbox|flyout/.test(n)) return { block: 'overlay', item: 'text-slot', control: true }
    if (/menu|list|tabs|tree|option|choice|picker|palette/.test(n)) return { block: 'surface', item: 'selectable', control: false }
    if (/button|switch|toggle|slider|input|field|select|spinner|stepper|control|search/.test(n)) return { block: 'control', item: 'text-slot', control: false }
    if (/badge|tag|status|alert|banner|chip|pill|label|warning|notice/.test(n)) return { block: 'tone-bearer', item: 'text-slot', control: false }
    return { block: 'surface', item: 'text-slot', control: true }
  }

  /** A scaffold for a component the kit does not have: tokens only, roles for
   *  the look, arrangement in the recipe. Passes audit:values by construction. */
  function scaffold(name, why) {
    const id = String(name).toLowerCase().replace(/\(.*?\)/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
    const roles = rolesFor(name)
    const css = [
      `/* .${id} — ${why}`,
      `   Composed from the Role Canvas: the LOOK comes from the data-role floors the`,
      `   kit already ships (surface · control · selectable · text-slot · overlay ·`,
      `   tone-bearer); this recipe owns arrangement only, in tokens. */`,
      `.${id} {`,
      `  display: flex;`,
      `  align-items: center;`,
      `  gap: ${T('--k-s-8')};`,
      `  padding: ${T('--k-s-8')} ${T('--k-s-12')};`,
      `  border-radius: ${T('--k-radius-md')};`,
      `}`,
      `.${id}__label {`,
      `  font-size: ${T('--k-type-small')};`,
      `  color: ${T('--k-fg-muted')};`,
      `}`,
      `.${id}__item + .${id}__item { margin-inline-start: ${T('--k-s-4')}; }`,
    ].join('\n')
    const html = [
      `<div class="${id}" data-role="${roles.block}">`,
      `  <span class="${id}__label" data-role="text-slot">${esc(title(name))}</span>`,
      roles.item === 'selectable'
        ? `  <div class="${id}__item" data-role="selectable" aria-selected="true">Selected</div>\n  <div class="${id}__item" data-role="selectable">Other</div>`
        : `  <span class="${id}__item" data-role="${roles.item}">…</span>`,
      roles.control ? `  <button class="btn btn--sm" type="button" data-role="control">Action</button>` : null,
      `</div>`,
    ].filter(Boolean).join('\n')
    return { id, css, html, roles }
  }

  /* ── the verdict ───────────────────────────────────────────────────────── */

  const provenanceLine = (r) => (r.provenance ?? []).filter((s) => s.layer !== 3).map((s) => s.source).join(' · ') || 'no core line — the derivation lists it as sourceless'

  const nameOf = (r) => r.page?.name ?? r.section
  function verdictFor(cl, matched) {
    /* Decided, on purpose: a core entry the derivation chose not to ship, with
     * the reason written down. The forge answers with the reason, not a build. */
    if (cl.decided.length && !cl.direct) {
      const d = cl.decided[0]
      return {
        verdict: 'decided',
        citations: [cite(d.cite)],
        reason: d.reason,
        say: `${d.name}: decided, on purpose, not to ship — ${d.reason} (Recorded in the derivation, where the gate accepts it as covered.)`,
      }
    }
    /* Covered by the token system, not by a component. */
    if (cl.token.length && !cl.direct) {
      const t = cl.token[0]
      return {
        verdict: 'token',
        citations: [cite(t.cite)],
        tokens: t.tokens,
        usage: `<svg class="icon" aria-hidden="true" width="var(--k-icon-md)" height="var(--k-icon-md)"><use href="#…"/></svg>`,
        say: `${t.name} is covered by the TOKEN system, not by a component: the icon set is a knob and the sizes are tokens (${t.tokens}). Use an inline <svg aria-hidden="true"> sized by the token; a component would be a second version of the same thing.`,
      }
    }
    /* A platform element that recipes merely EXTEND (backlink implements APG
     * Link, but "link" is <a>): the answer is the element, and the recipes are
     * listed as what the kit builds on it. A recipe named directly wins. */
    const platformFirst = cl.platform.length && !cl.direct
    const r = platformFirst ? null : cl.recipes[0]
    if (r) {
      const platform = cl.platform[0] ?? null
      const patterns = cl.patterns.map(cite)
      return {
        verdict: 'exists',
        recipe: r,
        citations: [...(r.provenance ?? []).map((s) => ({ layer: s.layer, source: s.source, url: s.url, note: s.because })), ...(platform && !(r.provenance ?? []).some((s) => s.layer === 1) ? [cite(platform)] : []), ...patterns],
        contract: r.apg ? { pattern: r.apg.pattern, url: r.apg.url, keys: r.apg.keys, aria: r.apg.aria, free: r.apg.free } : (r.apgNote ? { none: r.apgNote } : null),
        page: r.page ? `/components/${r.page.slug}` : null,
        pattern: patterns[0] ?? null,
        alternatives: cl.recipes.slice(1, 4).map((x) => ({ id: x.id, name: nameOf(x) })),
        usage: skeleton(r),
        say: `You already have this: ${nameOf(r)} (recipe "${r.id}"${r.element ? `, the kit's styling of <${r.element}>` : ''}). ` +
          `Its line: ${provenanceLine(r)}.` +
          (r.apg ? ` It implements APG ${r.apg.pattern}${r.apg.free ? ` — and ${r.apg.free.replace(/\.$/, '')}.` : '.'}` : r.apgNote ? ` No APG pattern applies: ${r.apgNote}` : '') +
          (patterns.length ? ` (${patterns[0].source} is a page pattern; this is the component it is built from.)` : '') +
          (r.page ? ` Page: /components/${r.page.slug}.` : ' It has no public page yet.') +
          (cl.recipes.length > 1 ? ` Also: ${cl.recipes.slice(1, 4).map(nameOf).join(', ')}.` : ''),
      }
    }
    if (cl.platform.length && (!cl.core.length || platformFirst)) {
      const el = cl.platform[0]
      const rules = floorFor(el.tag)
      const extendedBy = cl.recipes.slice(0, 5)
      const label = el.isAttr ? `the ${el.name} attribute` : `<${el.tag}>${el.type ? ` type="${el.type}"` : ''}`
      return {
        verdict: 'platform',
        element: el.name,
        citations: [cite(el), ...cl.core.map(cite)],
        floor: rules,
        extendedBy: extendedBy.map((x) => ({ id: x.id, name: nameOf(x), page: x.page ? `/components/${x.page.slug}` : null })),
        usage: elementSnippet(el),
        say: `The platform has this: ${label}. ` +
          (rules.length ? `The floor already styles it — ${rules[0].selector} { ${rules[0].body ?? '…'} } — ` : 'The floor should style it (it does not yet) — ') +
          `so it is not a component: use the element, do not build one.` +
          (extendedBy.length ? ` The kit builds on it in ${extendedBy.map(nameOf).join(', ')}.` : ''),
      }
    }
    if (cl.core.length) {
      const c = cl.core[0]
      const patterns = cl.core.filter((x) => x.kind === 'service' && x.pattern)
      const isPagePattern = patterns.length === cl.core.length
      const sc = isPagePattern ? null : scaffold(c.name, `named by ${cite(c).source} (${c.url}); no recipe in the kit covers it yet.`)
      return {
        verdict: 'core',
        citations: cl.core.map(cite),
        contract: c.kind === 'apg' ? { pattern: c.name, url: c.url, note: 'The pattern page carries the keyboard map and the ARIA it owes; the kit has no implementation to read them from yet.' } : { service: c.system, page: c.url },
        pagePattern: isPagePattern,
        scaffold: sc,
        say: isPagePattern
          ? `This is a page PATTERN, not a component: ${cite(c).source} (${c.url}). Compose it from the kit's components on a page — it does not become a recipe.`
          : `Not in the kit, but it may exist: ${cite(c).source} names it (${c.url}). ` +
            `That is a core line, so a recipe would pass the derivation gate. It owes what the source specifies; the scaffold below is composed from the kit's grammar (tokens + Role Canvas floors) and passes the value gate as written.`,
      }
    }
    if (cl.census.length) {
      const c = cl.census[0]
      const sc = scaffold(c.name, `a LOCAL EXTENSION. Only Open UI's census names it (${c.systems} of ${c.of} systems, ${c.pct}%): no HTML element, no APG pattern, no public-service component. The derivation gate will list it as sourceless.`)
      return {
        verdict: 'census',
        citations: cl.census.map(cite),
        scaffold: sc,
        say: `No normative or public-service source names this — Open UI's census does (${c.name}: ${c.systems} of ${c.of} systems, ${c.pct}%). ` +
          `It can exist as a LOCAL EXTENSION outside the core; the derivation gate will report it as sourceless until it earns a line or is cut. Scaffold below, from the kit's grammar.`,
      }
    }
    return null
  }

  /**
   * The public call. Returns a verdict object; `say` is the one-paragraph
   * answer, `citations` are what it rests on, and everything else is what an
   * agent needs to act.
   */
  function resolve(text) {
    const { words, spans, unknown } = match(text)
    /* Two spans that name the same thing are one thing ("avatar … initials"),
     * and a span whose concepts are a subset of another's adds nothing. */
    const classesAll = spans.map(classify)
    const key = (cl) => [...cl.recipes.map((r) => 'r:' + r.id), ...cl.platform.map((p) => 'p:' + p.name), ...cl.core.map((c) => 'c:' + c.url), ...cl.census.map((c) => 'o:' + c.name)].sort()
    const classes = []
    for (const cl of classesAll) {
      const k = key(cl)
      const dup = classes.find((o) => { const ok = key(o); return k.length && k.every((x) => ok.includes(x)) })
      if (dup) continue
      // a later, larger span absorbs an earlier subset
      const idx = classes.findIndex((o) => { const ok = key(o); return ok.length && ok.every((x) => k.includes(x)) })
      if (idx >= 0) classes[idx] = cl; else classes.push(cl)
    }
    const said = spans.filter((s) => s.deliberatelyEmpty && !s.concepts.length).map((s) => s.text)
    const base = { query: String(text), matched: classes.map((c) => c.text), unknown, refusedWords: said }

    const live = classes.filter((c) => c.recipes.length || c.platform.length || c.core.length || c.census.length || c.decided.length || c.token.length)
    if (!live.length) {
      return {
        ...base,
        verdict: 'none',
        citations: [],
        catalogues: [
          { layer: 1, source: 'MDN · HTML elements', url: data.catalogues.html.url },
          { layer: 2, source: 'WAI-ARIA APG patterns', url: data.catalogues.apg.url },
          { layer: 4, source: Object.keys(data.catalogues.services).join(' · '), url: Object.values(data.catalogues.services)[0]?.url },
        ],
        say: (said.length
          ? `"${said.join('", "')}" ${said.length > 1 ? 'are things' : 'is a thing'} the field ships and no layer names — not the platform, not APG, not a public service. The four-layer cut removed it on purpose; it does not become a component here. `
          : `No layer names this — not the platform (MDN), not WAI-ARIA APG, not GOV.UK / USWDS / NL Design System. `) +
          (unknown.length ? `Not understood: ${unknown.join(', ')}. ` : '') +
          `Describe it in the platform's or a service's terms, or build it outside the kit as a local extension.`,
      }
    }

    if (live.length === 1 || live.every((c) => c === live[0])) {
      const v = verdictFor(live[0], words)
      return { ...base, ...v }
    }

    /* COMPOSE — several things we have, arranged. Primary = the highest tier
     * (a card holds buttons, not the reverse), then the first named. */
    const each = live.map((cl) => ({ cl, v: verdictFor(cl, words) }))
    const withRecipe = each.filter((e) => e.v?.verdict === 'exists')
    const primaryE = [...withRecipe].sort((a, b) => TIER_RANK[b.v.recipe.tier] - TIER_RANK[a.v.recipe.tier])[0] ?? each[0]
    const others = each.filter((e) => e !== primaryE)
      // "a link … that goes back": the <a> is the Back link's own element, not a part of it
      .filter((e) => !(e.v?.verdict === 'platform' && primaryE.v?.recipe && e.cl.platform[0]?.tag === elementOf(primaryE.v.recipe)))
    const childHtml = others.map((e) => e.v?.usage ?? e.v?.scaffold?.html ?? `<!-- ${e.cl.text}: ${e.v?.verdict ?? 'unresolved'} -->`)
    const html = primaryE.v?.recipe ? skeleton(primaryE.v.recipe, childHtml) : [primaryE.v?.usage ?? '', ...childHtml].join('\n')
    const shown = [primaryE, ...others]
    if (shown.length === 1) return { ...base, ...primaryE.v }     // the rest was the primary said twice
    const have = shown.filter((e) => e.v?.verdict === 'exists').length
    return {
      ...base,
      verdict: 'compose',
      primary: primaryE.v,
      parts: others.map((e) => e.v),
      citations: shown.flatMap((e) => e.v?.citations ?? []),
      composition: html,
      say: `${shown.length} things, ${have === shown.length ? 'all of which you already have' : `${have} of which you have`}. ` +
        `Primary: ${primaryE.v?.recipe ? (primaryE.v.recipe.page?.name ?? primaryE.v.recipe.section) : primaryE.cl.text}` +
        (others.length ? `; inside it: ${others.map((e) => e.v?.recipe ? (e.v.recipe.page?.name ?? e.v.recipe.section) : `${e.cl.text} (${e.v?.verdict ?? 'unresolved'})`).join(', ')}.` : '.') +
        ` Composed from the kit's own classes below — a shape, not a specimen.` +
        (others.some((e) => e.v?.verdict === 'platform') ? ' Parts marked platform are elements, not components — use them as they are.' : ''),
    }
  }

  return {
    resolve,
    match,
    scaffold,
    skeleton,
    /** For tests and the page: every concept a form resolves to. */
    lookup: (phrase) => { const out = []; for (const f of forms(phrase)) for (const c of index.get(f) ?? []) if (!out.includes(c)) out.push(c); return out },
    size: { concepts: [...new Set([...index.values()].flat())].length, forms: index.size, vocabulary: vocab.size, recipes: recipes.length },
    layerName: (n) => LAYER_NAME[n],
  }
}

/** Node only — read the package's own data. The browser passes the JSON in. */
export async function loadForgeData() {
  const { readFileSync } = await import('node:fs')
  return JSON.parse(readFileSync(new URL('../data/forge.json', import.meta.url), 'utf8'))
}

/* ── the CLI ───────────────────────────────────────────────────────────────── */

const LABEL = { exists: 'EXISTS', platform: 'PLATFORM', core: 'MAY EXIST', census: 'LOCAL EXTENSION', decided: 'DECIDED NOT TO', token: 'A TOKEN', none: 'NO', compose: 'COMPOSE' }

/** Plain-text rendering shared by the CLI and the MCP tool. */
export function formatVerdict(v) {
  const out = []
  out.push(`${LABEL[v.verdict] ?? v.verdict.toUpperCase()} — ${v.query}`)
  out.push('')
  out.push(v.say)
  if (v.citations?.length) {
    out.push('')
    out.push('Citations:')
    for (const c of v.citations) out.push(`  L${c.layer} ${c.source}${c.note ? ` — ${c.note}` : ''}${c.url ? `\n     ${c.url}` : ''}`)
  }
  if (v.contract?.keys?.length) {
    out.push('')
    out.push(`Behaviour (APG ${v.contract.pattern} — ${v.contract.url}):`)
    for (const [k, what] of v.contract.keys) out.push(`  ${k.padEnd(18)} ${what}`)
    if (v.contract.aria?.length) { out.push('ARIA:'); for (const a of v.contract.aria) out.push(`  · ${a}`) }
  } else if (v.contract?.none) {
    out.push(''); out.push(`Behaviour: ${v.contract.none}`)
  }
  if (v.floor?.length) { out.push(''); out.push('The floor rule:'); for (const f of v.floor.slice(0, 3)) out.push(`  ${f.selector} { ${f.body ?? '…'} }`) }
  if (v.extendedBy?.length) { out.push(''); out.push(`The kit builds on it: ${v.extendedBy.map((x) => `${x.name}${x.page ? ` (${x.page})` : ''}`).join(' · ')}`) }
  if (v.reason) { out.push(''); out.push(`Reason: ${v.reason}`) }
  if (v.tokens) { out.push(''); out.push(`Tokens: ${v.tokens}`) }
  if (v.usage) { out.push(''); out.push('Usage:'); out.push(v.usage.split('\n').map((l) => '  ' + l).join('\n')) }
  if (v.scaffold) {
    out.push(''); out.push(`Scaffold (.${v.scaffold.id}) — CSS:`); out.push(v.scaffold.css.split('\n').map((l) => '  ' + l).join('\n'))
    out.push(''); out.push('Markup:'); out.push(v.scaffold.html.split('\n').map((l) => '  ' + l).join('\n'))
  }
  if (v.composition) { out.push(''); out.push('Composition:'); out.push(v.composition.split('\n').map((l) => '  ' + l).join('\n')) }
  if (v.unknown?.length) { out.push(''); out.push(`Not understood: ${v.unknown.join(', ')}`) }
  return out.join('\n')
}

export async function runForge(argv) {
  const json = argv.includes('--json')
  const text = argv.filter((a) => !a.startsWith('--')).join(' ').trim()
  if (!text) {
    console.error('usage: uicockpit forge "<describe the component>" [--json]')
    return 2
  }
  const forge = createForge(await loadForgeData())
  const v = forge.resolve(text)
  console.log(json ? JSON.stringify(v, null, 2) : formatVerdict(v))
  // Exit code carries the verdict: 0 you have it / may build it · 1 refused.
  return v.verdict === 'platform' || v.verdict === 'none' ? 1 : 0
}
